import Head from "next/head";
import { signIn, signOut, useSession } from "next-auth/react";

export default function Home() {
  const { data } = useSession();
  console.log("heres data", data);
  return (
    <div>
      <Head>
        <title>Kurilnica</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        {data?.user ? (
          <button onClick={() => signOut()}>Sign Out</button>
        ) : (
          <button onClick={() => signIn("google")}>Sign In</button>
        )}

        {data?.user?.name}
      </div>
    </div>
  );
}
