import { Box } from "@chakra-ui/react";
import { NextPageContext } from "next";
import { getSession, useSession } from "next-auth/react";
import Head from "next/head";
import AuthComponent from "../components/auth/AuthComponent";
import ChatComponent from "../components/chat/ChatComponent";
import type { Session } from "next-auth";

export default function Home() {
  const { data: session } = useSession();
  console.log("heres session", session);

  const reloadSessionHandler = () => {};

  return (
    <>
      <Head>
        <title>Kurilnica</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box>
        {session?.user.username ? (
          <ChatComponent />
        ) : (
          <AuthComponent
            session={session}
            reloadSession={reloadSessionHandler}
          />
        )}
      </Box>
    </>
  );
}

export async function getServerSideProps(context: NextPageContext) {
  // fetch session on serverside and return it as props so that useSession will have it available at render time
  const session = await getSession(context);

  return {
    props: {
      session,
    },
  };
}
